Repository boostcamp-2020/IssueTracker-14, pull requests merged in 2020-11, with the labels that each got.

#58 backend Dockerfile 설정
  .DS_Store
  README.md
  server/.dockerignore
  server/Dockerfile
Labels: BE

#59 [fix] dockerfile 수정
  server/Dockerfile
Labels: BE, Fix

#64 회원가입 로그인 기능 추가
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Common/View/InputView.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginEndPoint.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginInfo.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginResponse.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginUseCase.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Controller/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/PatternChecker.swift
Labels: Feat, iOS

#70 회원가입 화면 입력확인 결과에 따른 뷰 상태 변화 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/View/InputView.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Controller/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/PatternChecker.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpInfo.swift
Labels: Feat, iOS

#72 Coordinator 패턴 적용
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Model/Coordinator.swift
  iOS/IssueTracker/IssueTracker/Common/Model/MainCoordinator.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Controller/SignUpViewController.swift
Labels: Feat, PairProgramming, iOS

#69 React 폴더 구조 설계
  client/src/components/atoms/Button.js
  client/src/components/atoms/Dropdown.js
  client/src/components/atoms/Icon.js
  client/src/components/atoms/Image.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/Link.js
  client/src/components/templates/Footer.js
  client/src/components/templates/Header.js
  client/src/components/templates/Label.js
  client/src/pages/Issue/index.js
  client/src/pages/Label/index.js
  client/src/pages/Milestone/index.js
  client/src/pages/User/LoginForm.js
  client/src/pages/User/RegisterForm.js
  client/src/pages/User/index.js
  client/src/pages/index.js
Labels: Chore, FE

#75 Backend milestone crud 구현 및 router 연결, user controller error 처리
  server/controllers/milestone_controller.js
  server/controllers/user_controller.js
  server/routes/milestone/index.js
Labels: BE, Feat, Fix

#76 label CRUD API 구현
  server/controllers/label_controller.js
  server/controllers/user_controller.js
  server/routes/label/index.js
Labels: BE, Feat

#77 [FE] Chore: nginx 설정 파일 jenkins에서의 자동화로 불필요해진 파일 삭제
  client/default
Labels: Chore, FE

#78 Apple 로그인 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginEndPoint.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginInfo.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginUseCase.swift
  iOS/IssueTracker/IssueTracker/MainCoordinator.swift
Labels: Feat, PairProgramming, iOS

#80 Backend milestone, label crud api Fix
  server/controllers/label_controller.js
  server/controllers/milestone_controller.js
  server/routes/index.js
Labels: BE, Fix

#82 전 화면에 공통으로 사용될 Alert UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Extention/UIViewController+Alert.swift
Labels: Feat, PairProgramming, iOS

#84 회원가입 기능에 따른 UI 변화 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Extention/UIViewController+Alert.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Controller/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/PatternChecker.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpEndPoint.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpInfo.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpUseCase.swift
Labels: Feat, iOS

#83 Login결과에 따른 화면이동, Alert 구현완료
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginUseCase.swift
Labels: Feat, iOS

#86 [BE] Feat: milestone DB column 추가
  server/db/migrations/20201102130932-add-column-to-milestone.js
  server/db/models/milestone.js
Labels: BE, Feat

#85 Backend Join을 제외한 BE API 초안 완성
  server/app.js
  server/controllers/issue_controller.js
  server/controllers/issue_item_controller/issue_assignee_controller.js
  server/controllers/issue_item_controller/issue_comment_controller.js
  server/controllers/issue_item_controller/issue_label_controller.js
  server/controllers/issue_item_controller/issue_milestone_controller.js
  server/controllers/label_controller.js
  server/controllers/milestone_controller.js
  server/db/models/milestone.js
  server/middlewares/auth.js
  server/middlewares/passport_config.js
  server/routes/index.js
  server/routes/issue/index.js
  server/routes/milestone/index.js
  server/routes/user/index.js
Labels: BE, Feat

#89 Github Actions를 활용한 CI설정
  .DS_Store
  .github/.DS_Store
  .github/workflows/ios.yml
Labels: Chore, PairProgramming, iOS

#87 Backend join이 필요한 read api 작성 (필요한 attribute를 골라내는 작업 필요함.)
  server/controllers/issue_controller.js
  server/controllers/issue_item_controller/issue_assignee_controller.js
  server/controllers/issue_item_controller/issue_comment_controller.js
  server/controllers/issue_item_controller/issue_label_controller.js
  server/controllers/issue_item_controller/issue_milestone_controller.js
  server/controllers/label_controller.js
  server/controllers/milestone_controller.js
  server/controllers/user_controller.js
  server/db/migrations/20201028093014-create-label.js
  server/db/migrations/20201028093352-create-assignee.js
  server/db/migrations/20201028093404-create-label-has-issue.js
  server/db/migrations/20201028093724-set_associations.js
  server/db/models/assignee.js
  server/db/models/comment.js
  server/db/models/issue.js
  server/db/models/label.js
  server/db/models/label_has_issue.js
  server/db/models/milestone.js
  server/db/models/user.js
  server/routes/user/index.js
Labels: BE, DB, Feat, Fix

#90 yml파일 디렉토리 수정
  .github/workflows/ios.yml
  iOS/IssueTracker/PatternCheckerTests/PatternCheckerTests.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/SignUpUseCaseTests/SignUpUseCaseTests.swift
Labels: Chore, PairProgramming, iOS

#91 IssueCell UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCell.xib
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, PairProgramming, iOS

#93 [FE] Feat: Atomic design을 위한 폴더 및 파일 구조 설계
  client/src/components/atoms/Label.js
  client/src/components/atoms/Text.js
  client/src/components/index.js
  client/src/components/molecules/FormInput.js
  client/src/components/molecules/GithubLoginButton.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/RegisterForm.js
  client/src/libs/index.js
  client/src/stores/index.js
  client/src/utils/axios_util.js
Labels: FE, Feat

#94 Coordinator패턴 업데이트
  .DS_Store
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/HomeTabBarCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/LabelCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/MainCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/MileStoneCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/NavigationCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/SettingCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/TabBarCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/HomeTabBarController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
  iOS/IssueTracker/IssueTracker/SettingScene/SettingViewController.swift
Labels: Feat, iOS

#95 이슈 목록 화면 CollectionView UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/View/PaddingLabel.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCell.xib
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, iOS

#99 이슈 목록 요청 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/Coordinator/MainCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListEndPoint.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpEndPoint.swift
  iOS/IssueTracker/SignUpUseCaseTests/SignUpUseCaseTests.swift
Labels: Feat, iOS

#100 [BE] Fix: issues get api 오류 수정
  server/controllers/issue_controller.js
Labels: BE, Fix

#102 [BE] Feat: issue에 description column 추가
  server/controllers/issue_controller.js
  server/db/migrations/20201104114047-add_description_to_issue.js
Labels: BE, DB, Feat

#103 [BE] Fix: issue 생성시 description 생성 안되는거 수정
  server/controllers/issue_controller.js
Labels: BE, DB, Fix

#104 Backend issue description 생성 수정
  server/db/models/issue.js
Labels: BE, Chore, DB, Fix

#105 Backend cors 설정
  server/app.js
Labels: BE, Feat

#106 Backend to Dev merge
  server/.dockerignore
  server/.env
  server/.gitignore
  server/Dockerfile
  server/app.js
  server/controllers/issue_controller.js
  server/controllers/issue_item_controller/issue_assignee_controller.js
  server/controllers/issue_item_controller/issue_comment_controller.js
  server/controllers/issue_item_controller/issue_label_controller.js
  server/controllers/issue_item_controller/issue_milestone_controller.js
  server/controllers/label_controller.js
  server/controllers/milestone_controller.js
  server/controllers/user_controller.js
  server/db/migrations/20201028093014-create-label.js
  server/db/migrations/20201028093352-create-assignee.js
  server/db/migrations/20201028093404-create-label-has-issue.js
  server/db/migrations/20201028093724-set_associations.js
  server/db/migrations/20201102130932-add-column-to-milestone.js
  server/db/migrations/20201104114047-add_description_to_issue.js
  server/db/models/assignee.js
  server/db/models/comment.js
  server/db/models/issue.js
  server/db/models/label.js
  server/db/models/label_has_issue.js
  server/db/models/milestone.js
  server/db/models/user.js
  server/middlewares/auth.js
  server/middlewares/passport_config.js
  server/routes/index.js
  server/routes/issue/index.js
  server/routes/label/index.js
  server/routes/milestone/index.js
  server/routes/user/index.js
Labels: BE

#109 이슈 Close 기능 구현
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkRequest.swift
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListEndPoint.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
Labels: Feat, iOS

#114 Frontend login 화면 구성
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/atoms/Button.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/InputLabel.js
  client/src/components/atoms/Text.js
  client/src/components/index.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/FormInput.js
  client/src/components/molecules/LoginButton.js
  client/src/components/molecules/LoginLinkBar.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/Title.js
  client/src/constants/colors.js
  client/src/constants/url.js
  client/src/index.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/RegisterPage.js
  client/src/pages/User/index.js
  client/src/pages/index.js
Labels: FE, Feat

#117 Frontend 회원가입 화면 구성
  client/src/App.js
  client/src/components/atoms/Icon.js
  client/src/components/molecules/GithubLoginButton.js
  client/src/components/molecules/LoginButton.js
  client/src/components/molecules/SignUpButton.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/SignUpForm.js
  client/src/constants/icons.js
  client/src/pages/User/SignUpPage.js
Labels: FE, Feat, Refactor, Style

#112 로그인 기능 테스트코드 작성
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/LoginUseCaseTests/Info.plist
  iOS/IssueTracker/LoginUseCaseTests/LoginUseCaseTests.swift
Labels: Test, iOS

#115 이슈 목록 화면 기능 테스트 코드 작성
  iOS/IssueTracker/IssueListUseCaseTests/Info.plist
  iOS/IssueTracker/IssueListUseCaseTests/IssueListUseCaseTests.swift
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
Labels: Test, iOS

#123 비동기 테스트 추가
  iOS/IssueTracker/.swiftlint.yml
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/Issue+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/IssueListUseCaseError+Equatable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/IssueResponse+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/LoginResponse+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/LoginUseCaseError+Equatable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/MileStone+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/NetworkServiceError+Equtable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Info.plist
  iOS/IssueTracker/IssueTrackerUnitTests/IssueListUseCaseTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/LoginUseCaseTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Mock/MockNetworkService.swift
  iOS/IssueTracker/IssueTrackerUnitTests/NetworkServiceTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/PatternCheckerTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/SignUpUseCaseTests.swift
  iOS/IssueTracker/LoginUseCaseTests/Info.plist
  iOS/IssueTracker/PatternCheckerTests/Info.plist
  iOS/IssueTracker/SignUpUseCaseTests/Info.plist
Labels: PairProgramming, Test, iOS

#125 Frontend 로그인 기능 구현 (초안)
  client/src/App.js
  client/src/components/atoms/Button.js
  client/src/components/atoms/Icon.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/Text.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/GithubLoginButton.js
  client/src/components/molecules/LoginButton.js
  client/src/components/molecules/LoginLinkBar.js
  client/src/components/molecules/SignUpButton.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/RegisterForm.js
  client/src/components/organisms/Title.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/RegisterPage.js
  client/src/stores/auth.js
Labels: FE, Feat, Fix

#128 이슈 상세화면 하단 뷰 UI 구현
  .DS_Store
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/View/PaddingLabel.swift
  iOS/IssueTracker/IssueTracker/Common/View/ShadowButton.swift
  iOS/IssueTracker/IssueTracker/Common/View/ShadowView.swift
  iOS/IssueTracker/IssueTracker/IssueDetailPullUpScene/IssueDetailPullUPViewController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
Labels: Feat, iOS

#127 이슈 상세 화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailTableViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueInfoView.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, iOS

#131 StoryBoard 충돌 수정
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
Labels: Fix, PairProgramming, iOS

#129 [FE] Chore: Async Await 사용을 위한 Webpack Polyfill 설정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/User/IssuesPage.js
  client/src/pages/User/LoginPage.js
  client/src/stores/user.js
  client/src/utils/axios_util.js
  client/src/utils/myAxios.js
  client/webpack.config.js
  server/app.js
Labels: Chore, FE

#124 [BE] Refactor: API Status Code 수정
  server/controllers/issue_controller.js
  server/controllers/issue_item_controller/issue_assignee_controller.js
  server/controllers/issue_item_controller/issue_comment_controller.js
  server/controllers/issue_item_controller/issue_label_controller.js
  server/controllers/milestone_controller.js
  server/controllers/user_controller.js
Labels: BE, Refactor

#135 [BE] Feat: 특정 issue, label, milestone 추가
  client/src/App.js
  client/src/components/atoms/Label.js
  client/src/components/atoms/Link.js
  client/src/components/molecules/SignUpButton.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/SignUpForm.js
  client/src/constants/url.js
  client/src/pages/User/IssuesPage.js
  client/src/pages/User/LoginPage.js
  client/src/stores/index.js
  client/src/stores/user.js
  client/src/utils/myAxios.js
  server/controllers/issue_controller.js
  server/controllers/label_controller.js
  server/controllers/milestone_controller.js
  server/middlewares/passport_config.js
  server/package.json
  server/routes/issue/index.js
  server/routes/label/index.js
  server/routes/milestone/index.js
Labels: BE, FE, Feat, Fix

#136 이슈 상세화면 하단뷰 추가
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueDetailPullUpScene/IssueDetailPullUPViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetailPullUpScene/IssueDetailPullUpViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
Labels: Feat, iOS

#139 [FE] 화면 구성
  client/src/App.js
  client/src/components/atoms/Button.js
  client/src/components/atoms/Checkbox.js
  client/src/components/atoms/Dropdown.js
  client/src/components/atoms/Icon.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/InputLabel.js
  client/src/components/molecules/ClearIssueFilter.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/NavigationWrapperLink.js
  client/src/components/molecules/NewIssueButton.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/IssueMenuDropdowns.js
  client/src/components/organisms/IssueWrapper.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/NavigationWrapperInput.js
  client/src/components/organisms/SignUpForm.js
  client/src/constants/icons.js
  client/src/pages/Issue/IssuesPage.js
  client/src/pages/Issue/index.js
  client/src/pages/User/IssuesPage.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/SignUpPage.js
Labels: Chore, FE, Feat, Style

#145 [FE] 라벨 Atom 생성
  client/src/components/atoms/Label.js
  client/src/components/molecules/Dropdown.js
Labels: FE, Feat

#146 [FE] Fix: Label에서 Children이 길어지면 두줄로 변경되는 에러 수정
  client/src/components/atoms/Label.js
Labels: FE, Fix

#147 new milestone page 초안
  client/src/App.js
  client/src/components/atoms/Label.js
  client/src/components/atoms/index.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/LoginButton.js
  client/src/components/molecules/NavigationWrapperLink.js
  client/src/components/molecules/NewMilestoneButton.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/NewMilestoneForm.js
  client/src/pages/Milestone/NewMilestonePage.js
  client/src/pages/Milestone/index.js
  client/src/stores/user.js
  server/middlewares/passport_config.js
Labels: FE

#142 이슈 상세정보 요청 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Model/UseCaseError.swift
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailTableViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueEndPoint.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Model/LoginUseCase.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/Model/SignUpUseCase.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/UseCaseError+Equtable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/NetworkServiceTests.swift
Labels: Feat, iOS

#150 [FE] Refactor: Atomic design refactoring
  client/src/components/atoms/index.js
  client/src/components/molecules/ButtonDiv.js
  client/src/components/molecules/ClearIssueFilter.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/GithubLoginButton.js
  client/src/components/molecules/LoginButton.js
  client/src/components/molecules/NewIssueButton.js
  client/src/components/molecules/NewMilestoneButton.js
  client/src/components/molecules/SignUpButton.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/IssueMenuDropdowns.js
  client/src/components/organisms/IssueWrapper.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/NavigationWrapperInput.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/NewIssueOptions.js
  client/src/components/organisms/NewMilestoneForm.js
  client/src/components/organisms/SignUpForm.js
  client/src/components/organisms/Title.js
  client/src/components/organisms/index.js
  client/src/pages/Issue/IssuesPage.js
Labels: FE, PairProgramming, Refactor

#151 이슈 생성 화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCreateViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, iOS

#152 이슈 상세화면 다중선택 편집 기능 구현
  .DS_Store
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewEditTabBar.swift
Labels: Feat, iOS

#158 이슈 상세화면 버그 수정
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Fix, iOS

#153 [FE] Feat: New milstone page + New milstone create 기능 추가
  client/src/App.js
  client/src/components/atoms/Button.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/InputLabel.js
  client/src/components/atoms/Line.js
  client/src/components/atoms/Text.js
  client/src/components/atoms/TextArea.js
  client/src/components/atoms/index.js
  client/src/components/molecules/ButtonDiv.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/FormTextArea.js
  client/src/components/molecules/NavigationWrapperLink.js
  client/src/components/molecules/Title.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/IssueMenuDropdowns.js
  client/src/components/organisms/LoginForm.js
  client/src/components/organisms/NewMilestoneForm.js
  client/src/components/organisms/index.js
  client/src/constants/colors.js
  client/src/pages/Milestone/NewMilestonePage.js
  client/src/pages/User/GithubCallbackPage.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/SignUpPage.js
  client/src/stores/milestone.js
  client/src/stores/user.js
  server/app.js
  server/controllers/user_controller.js
  server/middlewares/passport_config.js
Labels: FE, Feat

#167 이슈 생성 화면 마크업
  client/src/components/atoms/Button.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/InputLabel.js
  client/src/components/atoms/Text.js
  client/src/components/atoms/index.js
  client/src/components/molecules/FileInput.js
  client/src/components/molecules/FormTextArea.js
  client/src/components/molecules/index.js
  client/src/components/organisms/NewIssueForm.js
  client/src/pages/Issue/NewIssuePage.js
Labels: FE, Feat

#173 [FE] Web - Issue 상세 페이지 Container화
  client/src/components/molecules/Container.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/IssueData.js
  client/src/components/molecules/index.js
  client/src/components/organisms/DropdownCluster.js
  client/src/components/organisms/IssueContent.js
  client/src/components/organisms/IssueMenu.js
  client/src/components/organisms/IssueMenuDropdowns.js
  client/src/components/organisms/IssueWrapper.js
  client/src/components/organisms/index.js
  client/src/constants/icons.js
  client/src/pages/Issue/IssuesPage.js
Labels: FE, Feat, Style

#176 [FE] Refactor: Page의 원자들을 index에서 불러오도록 수정
  client/src/pages/Issue/IssuesPage.js
  client/src/pages/Issue/NewIssuePage.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/SignUpPage.js
Labels: FE, Refactor

#179 Github login 구현
  client/src/App.js
  client/src/components/organisms/LoginForm.js
  server/controllers/issue_controller.js
  server/controllers/user_controller.js
Labels: FE, Feat

#184 [iOS] Feat: 레이블&마일스톤 편집 화면 공통부분 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/View/AnimatableButton.swift
  iOS/IssueTracker/IssueTracker/Common/View/ShadowButton.swift
  iOS/IssueTracker/IssueTracker/EditingScene/EditingView.swift
  iOS/IssueTracker/IssueTracker/EditingScene/EditingViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
Labels: Feat, iOS

#183 이슈생성 페이지, 마일스톤 생성 페이지 컴포넌트 css 수정
  client/src/components/atoms/Button.js
  client/src/components/atoms/InputLabel.js
  client/src/components/molecules/FileInput.js
  client/src/components/molecules/FormTextArea.js
  client/src/components/molecules/Tabs.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/NewMilestoneForm.js
Labels: FE, Fix

#185 이슈 상세화면 스크롤기능 추가
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetailPullUpScene/IssueDetailPullUpViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
Labels: Feat, iOS

#187 레이블 관리 화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/LabelCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/Label.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
Labels: Feat, iOS

#191 이슈 상세화면 스크롤 버그 수정
  iOS/IssueTracker/IssueTracker/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/IssueListUseCase.swift
Labels: Fix, iOS

#192 [FE] Fix: Dropdown 에러 수정
  client/src/components/atoms/Button.js
  client/src/components/molecules/Dropdown.js
  client/src/components/organisms/IssueMenu.js
Labels: FE, Fix

#197 이슈 생성화면 옵션클릭 UI 구현 - 진행중
  client/src/App.js
  client/src/components/atoms/Button.js
  client/src/components/atoms/Image.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/DropdownItem.js
  client/src/components/molecules/DropdownWithText.js
  client/src/components/molecules/IssueData.js
  client/src/components/molecules/Overlay.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/NewIssueOptions.js
  client/src/pages/Issue/NewIssuePage.js
  client/src/stores/issue.js
  server/routes/user/index.js
Labels: FE, Feat

#198 마일스톤 관리 화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Extention/String+customDateFormat.swift
  iOS/IssueTracker/IssueTracker/Common/Extention/UIViewController+alert.swift
  iOS/IssueTracker/IssueTracker/Coordinator/MileStoneCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStone.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/MileStone+Encodable.swift
Labels: Feat, iOS

#199 NewIssueForm 에러 수정
  client/src/components/organisms/NewIssueForm.js
Labels: FE, Fix

#201 랜덤 색상 출력 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Extention/UIColor+hex.swift
  iOS/IssueTracker/IssueTracker/EditingScene/Model/RandomHexColorGenerator.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
Labels: Feat, iOS

#203 레이블 목록 네트워크 요청으로 목록 받아오기 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Extention/UIColor+hex.swift
  iOS/IssueTracker/IssueTracker/Coordinator/LabelCoordinator.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/Label.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEndPoint.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListUseCase.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelResponse.swift
Labels: Feat, iOS

#209 이슈생성화면의 Assignee, Label, Milestone 팝업 구현
  client/src/components/atoms/Label.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/DropdownItem.js
  client/src/components/molecules/DropdownWithText.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/NewIssueOptions.js
  client/src/constants/icons.js
  client/src/stores/issue.js
  server/controllers/issue_controller.js
Labels: FE, Feat

#210 [FE] Issue 상세 페이지 체크박스 수정
  client/src/components/atoms/Button.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/Label.js
  client/src/components/molecules/FormDiv.js
  client/src/components/molecules/IssueData.js
  client/src/components/molecules/NavigationWrapperLink.js
  client/src/components/organisms/IssueContent.js
  client/src/components/organisms/IssueMenu.js
  client/src/components/organisms/LabelNavigation.js
  client/src/components/organisms/index.js
  client/src/constants/icons.js
  client/src/pages/Issue/IssuesPage.js
  client/src/pages/Label/LabelPage.js
  client/src/pages/Label/index.js
  client/src/utils/decideFontColorFromHexa.js
Labels: FE, Feat

#215 이슈 상세화면 진행중
  client/src/App.js
  client/src/components/molecules/DropdownWithText.js
  client/src/components/molecules/IssueData.js
  client/src/components/organisms/EditIssueForm.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/index.js
  client/src/pages/Issue/EditIssuePage.js
Labels: FE, Feat

#216 [FE] Feat: 셀렉트 박스로 선택후에 status 변경 가능
  client/src/components/organisms/IssueMenu.js
  client/src/stores/issue.js
Labels: FE, Feat

#207 필터선택화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/FilterScene/FilterTableViewController.swift
  iOS/IssueTracker/IssueTracker/FilterScene/FilterTableViewHeaderFooterView.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, iOS

#211 마일스톤 편집화면 UI 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/MileStoneCoordinator.swift
  iOS/IssueTracker/IssueTracker/EditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/EditingScene/MileStoneEditingView.swift
  iOS/IssueTracker/IssueTracker/EditingScene/MileStoneEditingView.xib
  iOS/IssueTracker/IssueTracker/FilterScene/FilterTableViewController.swift
  iOS/IssueTracker/IssueTracker/FilterScene/FilterTableViewHeaderFooterView.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Feat, iOS

#208 레이블 관련 기능 연동
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkRequest.swift
  iOS/IssueTracker/IssueTracker/Coordinator/LabelCoordinator.swift
  iOS/IssueTracker/IssueTracker/EditingScene/LabelEditViewController.swift
  iOS/IssueTracker/IssueTracker/EditingScene/LabelEditingView.swift
  iOS/IssueTracker/IssueTracker/EditingScene/LabelEditingView.xib
  iOS/IssueTracker/IssueTracker/EditingScene/LabelUseCaseType.swift
  iOS/IssueTracker/IssueTracker/EditingScene/Model/RandomHexColorGenerator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/Label.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEndPoint.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListResponse.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListUseCase.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
Labels: Feat, iOS

#219 Github 로그인 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Coordinator/MainCoordinator.swift
  iOS/IssueTracker/IssueTracker/LoginScene/Controller/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/GithubLoginViewController.swift
Labels: Feat, PairProgramming, iOS

#220 전체 파일 역할별 폴더 분리
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Coordinator/HomeTabBarCoordinator.swift
  iOS/IssueTracker/IssueTracker/Common/Coordinator/NavigationCoordinator.swift
  iOS/IssueTracker/IssueTracker/Common/Coordinator/TabBarCoordinator.swift
  iOS/IssueTracker/IssueTracker/Common/View/DimmedViewController.swift
  iOS/IssueTracker/IssueTracker/Common/View/EditingView.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/FilterScene/FilterTableViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/Issue.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueDetailScene/IssueDetailPullUpViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueDetailScene/IssueDetailTableViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueDetailScene/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueDetailScene/IssueInfoView.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueEndPoint.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListUseCase.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelCoordinator.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditingView.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditingView.xib
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelUseCaseType.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/RandomHexColorGenerator.swift
  iOS/IssueTracker/IssueTracker/LoginScene/GithubLoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginCoordinator.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginEndPoint.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginInfo.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginResponse.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginUseCase.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneCoordinator.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.xib
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SettingScene/SettingCoordinator.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/PatternChecker.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpEndPoint.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpInfo.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpUseCase.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpViewController.swift
Labels: Chore, PairProgramming, iOS

#223 필터선택 UI 짤림 현상 수정
  .DS_Store
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueListScene/FilterScene/FilterTableViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/FilterScene/FilterViewController.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCoordinator.swift
Labels: Fix, iOS

#227 키보드 관련 버그 해결, 화면크기 대응
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/View/DimmedViewController.swift
  iOS/IssueTracker/IssueTracker/Common/View/InputView.swift
  iOS/IssueTracker/IssueTracker/Common/View/KeyboardObservableViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditingView.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditingView.xib
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpViewController.swift
Labels: Fix, iOS

#230 마일스톤 수정, 생성 초기화 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Extention/String+customDateFormat.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStone.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneCoordinator.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.xib
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneUseCaseType.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEndPoint.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListResponse.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListUsecase.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
Labels: Feat, iOS

#228 레이블 생성, 수정, 삭제 기능 테스트
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/Label+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/LabelListUseCaseTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/LabelUseCaseTests.swift
Labels: Test, iOS

#232 앱 아이콘 설정, 앱 이름 수정
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  iOS/IssueTracker/IssueTracker/Info.plist
Labels: Chore, iOS

#231 [FE] Label 생성 페이지 구현
  ,
  client/src/App.js
  client/src/components/molecules/LabelModal.js
  client/src/components/molecules/NavigationWrapperLink.js
  client/src/components/molecules/index.js
  client/src/components/organisms/LabelCard.js
  client/src/components/organisms/LabelContent.js
  client/src/components/organisms/LabelMenu.js
  client/src/components/organisms/LabelNavigation.js
  client/src/components/organisms/index.js
  client/src/constants/colors.js
  client/src/pages/Label/LabelPage.js
  client/src/stores/label.js
  client/src/utils/makeRandomColor.js
  client/src/utils/myAxios.js
Labels: FE, Feat

#237 이슈 상세 화면 진행중
  client/src/App.js
  client/src/components/atoms/Image.js
  client/src/components/atoms/Text.js
  client/src/components/molecules/IssueCard.js
  client/src/components/molecules/Tabs.js
  client/src/components/organisms/EditIssueForm.js
  client/src/components/organisms/EditIssueHeader.js
  client/src/components/organisms/EditIssueOptions.js
  client/src/components/organisms/EditIssueTitle.js
  client/src/components/organisms/NewIssueForm.js
  client/src/components/organisms/index.js
  client/src/constants/colors.js
  client/src/pages/Issue/EditIssuePage.js
  client/src/pages/Issue/NewIssuePage.js
  client/src/stores/comment.js
  client/src/stores/index.js
  client/src/stores/issue.js
  client/src/utils/calculateTime.js
  server/config/config.js
  server/controllers/issue_controller.js
  server/controllers/issue_item_controller/issue_comment_controller.js
  server/db/migrations/20201112112045-set-comment-type-long.js
  server/db/models/comment.js
Labels: FE, Feat

#238 제목이 비어있어도 레이블이 생성되는 문제
  iOS/IssueTracker/IssueTracker/Common/View/AnimatableButton.swift
  iOS/IssueTracker/IssueTracker/Common/View/EditingView.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelEditingScene/LabelEditingView.swift
Labels: Fix, iOS

#239 [FE] Label Page 기능 구현 완료
  client/src/components/molecules/LabelModal.js
  client/src/components/organisms/LabelCard.js
  client/src/components/organisms/LabelContent.js
  client/src/components/organisms/LabelNavigation.js
  client/src/pages/Label/LabelPage.js
Labels: FE, Feat

#236 UIColor+hex에서 hexCode의 count가 0일때 removeFirst fatal에러 예외처리
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Extention/UIColor+hex.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpPatternChecker.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpViewController.swift
  iOS/IssueTracker/IssueTrackerUnitTests/PatternCheckerTests.swift
Labels: Fix, iOS

#243 [FE] Label 페이지 생성
  client/src/components/atoms/Button.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/Label.js
  client/src/components/molecules/Container.js
  client/src/components/molecules/Dropdown.js
  client/src/components/molecules/DropdownWithText.js
  client/src/components/molecules/LabelModal.js
  client/src/components/organisms/IssueMenu.js
  client/src/components/organisms/LabelCard.js
  client/src/components/organisms/LabelContent.js
  client/src/components/organisms/LabelNavigation.js
  client/src/components/organisms/LoginForm.js
  client/src/constants/colors.js
  client/src/pages/Issue/EditIssuePage.js
  client/src/pages/Issue/IssuesPage.js
  client/src/pages/Issue/NewIssuePage.js
  client/src/pages/Milestone/EditMilestonePage.js
  client/src/pages/Milestone/MilestonePage.js
  client/src/pages/Milestone/NewMilestonePage.js
  client/src/pages/User/LoginPage.js
  client/src/pages/User/SignUpPage.js
Labels: FE, Feat

#247 [FE] Refactor
  client/src/components/atoms/Button.js
  client/src/components/molecules/IssueCard.js
  client/src/components/molecules/LabelModal.js
  client/src/pages/Label/LabelPage.js
  server/controllers/user_controller.js
  server/middlewares/passport_config.js
Labels: FE, Refactor

#249 코멘트 생성 화면 구현
  client/src/components/atoms/Text.js
  client/src/components/atoms/TextArea.js
  client/src/components/organisms/EditIssueForm.js
  client/src/components/organisms/EditIssueHeader.js
  client/src/components/organisms/EditIssueOptions.js
  client/src/components/organisms/NewCommentForm.js
  client/src/components/organisms/NewIssueOptions.js
  client/src/components/organisms/index.js
  client/src/pages/Issue/EditIssuePage.js
  client/src/stores/comment.js
  client/src/utils/calculateTime.js
Labels: FE, Feat

#250 assign yourself 구현
  client/src/components/molecules/DropdownWithText.js
  client/src/pages/Issue/NewIssuePage.js
  client/src/stores/issue.js
Labels: FE, Feat

#251 [FE] Refactor: Organisms 폴더 세분화
  client/src/App.js
  client/src/components/atoms/Input.js
  client/src/components/molecules/ContentEmpty.js
  client/src/components/molecules/index.js
  client/src/components/organisms/DropdownCluster.js
  client/src/components/organisms/Issue/EditIssueForm.js
  client/src/components/organisms/Issue/EditIssueHeader.js
  client/src/components/organisms/Issue/EditIssueTitle.js
  client/src/components/organisms/Issue/IssueContent.js
  client/src/components/organisms/Issue/IssueFilterAndSearch.js
  client/src/components/organisms/Issue/IssueMenu.js
  client/src/components/organisms/Issue/NewCommentForm.js
  client/src/components/organisms/Issue/NewIssueForm.js
  client/src/components/organisms/Issue/NewIssueOptions.js
  client/src/components/organisms/Label/LabelCard.js
  client/src/components/organisms/Label/LabelContent.js
  client/src/components/organisms/Label/LabelMenu.js
  client/src/components/organisms/Label/LabelNavigation.js
  client/src/components/organisms/Milestone/EditMilestoneForm.js
  client/src/components/organisms/Milestone/MilestoneContent.js
  client/src/components/organisms/Milestone/MilestoneMenu.js
  client/src/components/organisms/Milestone/NewMilestoneForm.js
  client/src/components/organisms/User/LoginForm.js
  client/src/components/organisms/User/SignUpForm.js
  client/src/components/organisms/index.js
  client/src/pages/Issue/IssuesPage.js
Labels: FE, Refactor

#245 마일스톤 기능 관련 테스트 코드 작성
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingPatternChecker.swift
  iOS/IssueTracker/IssueTrackerUnitTests/Extension/MileStone+Encodable.swift
  iOS/IssueTracker/IssueTrackerUnitTests/MileStoneEditingPatternCheckerTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/MileStoneListUseCaseTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/MileStoneUseCaseTests.swift
  iOS/IssueTracker/IssueTrackerUnitTests/SingUpPatternCheckerTests.swift
Labels: Test, iOS

#252 [FE] Feat: Webpack alias 기능 추가
  client/octocat.png
  client/package-lock.json
  client/package.json
  client/webpack.config.js
Labels: FE, Feat

#254 로그아웃 기능 구현
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/Coordinator/HomeTabBarCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueCoordinator.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListUseCase.swift
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginCoordinator.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditingView.swift
  iOS/IssueTracker/IssueTracker/SettingScene/SettingCoordinator.swift
  iOS/IssueTracker/IssueTracker/SettingScene/SettingViewController.swift
Labels: Feat, iOS

#257 로그아웃시 발생하는 메모리릭 해결
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
  iOS/IssueTracker/IssueTracker/SettingScene/SettingViewController.swift
Labels: Fix, iOS

#259 리스트 리로드 기능 추가
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/LabelListScene/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneListViewController.swift
Labels: Feat, PairProgramming, iOS

#261 .DSStore 제거
  .DS_Store
Labels: Chore, iOS

#263 애플로그인 오류, 키보드 밖을 터치해도 키보드가 내려가지 않는 현상
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/SignUpScene/SignUpViewController.swift
Labels: Fix, iOS

#264 마일스톤 텍스트 바인딩 수정
  .DS_Store
  iOS/IssueTracker/IssueTracker/MileStoneListScene/MileStoneEditingScene/MileStoneEditViewController.swift
Labels: Fix, iOS

#266 iOS브런치 README 업데이트
  README.md
  iOS/IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker.xcscheme
  iOS/IssueTracker/IssueTracker/IssueListScene/IssueListViewController.swift
Labels: Docs
